version: '3.9'

###
# Common Configs
###
x-environment: &default-tz-puid-pgid
  TZ: ${TZ:-America/Denver}
  PUID: ${PUID:-1000}
  PGID: ${PGID--1000}
  GUID: ${GUID:-1000}


services:
###
# Portainer - Manage docker contsainers and stack
###
  portainer:
    image: portainer/portainer-ce:linux-arm64-2.16.2-alpine
    container_name: portainer
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1000}
      - GUID=${GUID:-1000}
      - TZ=${TZ:-America/Denver}
    network_mode: host
    volumes:
      - "/var/lib/docker:/var/lib/docker"
      - "portainer_data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

###
# Plex- Media Server
###  
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1000}
      - GUID=${GUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    network_mode: host
    volumes:
      - "${MEDIA_DIR}/media/movies:/movies"
      - "${MEDIA_DIR}/media/tv:/tv"
      - "/var/lib/docker:/var/lib/docker"
      - "plex_config:/config"

###
# Plex Meta Manager - organize and present media
###
  plex_meta_manager:
    image: "lscr.io/linuxserver/plex-meta-manager:latest"
    container_name: plex_meta_manager
    restart: unless-stopped
    network_mode: host
    depends_on:
      - plex
    environment:
      - PUID=${PUID:-1000}
      - GUID=${GUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/Denver}
      - PMM_CONFIG=${PMM_CONFIG:-/config/config.yml} #optional
      - PMM_TIME=run #$${PMM_TIME:-03:00} #optional
      - PMM_RUN=${PMM_RUN:-False} #optional
      - PMM_TEST=${PMM_TEST:-False} #optional
      - PMM_NO_MISSING=${PMM_NO_MISSING:-False} #optional
    volumes:
      - ${DOCKER_DIR}/plex_meta_manager/config/config.yml:/config/config.yml
      - ${DOCKER_DIR}/plex_meta_manager/config:/config

###
# dozzle, unified log interface
# ##
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID:-1000}
      - GUID=${GUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/Denver}
      - DOZZLE_TAILSIZE=300
      - DOZZLE_LEVEL=debug # info trace
    # ports:
      # - 8080:8080
 
###
#  tautulli - Utilities for Plex
###  
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    network_mode: host
    depends_on: 
      - plex
    environment:
      - PUID=${PUID:-1000}
      - PGID=${GUID:-1000}
      - GUID=${GUID:-1000} 
      - TZ=$={TZ:-America/Denver}
    volumes:
      - ${DOCKER_DIR}/tautulli/config/:/config/
        # ports:
        # - 8181:8181
    restart: unless-stopped

###
# Heimdall
###
  heimdall: 
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    ports:
      - 8010:80
      - 8443:443 
    volumes:
      - $DOCKER_DIR/appdata/heimdall/config:/config
    environment:
      - PUID=${PUID:-1000}
      - PGID=${GUID:-1000}
      - GUID=${GUID:-1000} 
      - TZ=${TZ:-America/Denver}
    restart: unless-stopped
    #networks:
    #  - default

###
# System Volumes
###
volumes:
  plex_config:
    external: true
  portainer_data:
    external: true
  
  ###
  # Networks
  ###
  #networks:
  #  default:
  #    driver: bridge